### ISSUE TITLE
Lua error opon login

### ISSUE THREAD

**Issue by Gennoken** [muhmiauwauWOW/GreatVaultList#10]
upon login

1x ...faceGreatVaultList/GreatVaultListOptions.lua:71: attempt to call method 'SetValueChangedCallback' (a nil value)

and this too

2x Blizzard_Settings_Shared/Blizzard_Setting.lua:383: 'variableTbl' argument must be a table.
[string "=[C]"]: in function `assert'
[string "@Blizzard_Settings_Shared/Blizzard_Setting.lua"]:383: in function `Init'
[string "@Blizzard_SharedXMLBase/Mixin.lua"]:28: in function <Blizzard_SharedXMLBase/Mixin.lua:26>
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:197: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:155>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:98: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:97>
[string "=(tail call)"]: ?
[string "@GreatVaultList/GreatVaultListOptions.lua"]:67: in function `init'

**Comment by muhmiauwau** [comment]
Hi  @Gennoken, thank you for reporting this bug, it is fixed with version 2.4.6.

**Comment by Gennoken** [comment]
thx for being quick !
