### ISSUE TITLE
Incompatible with Astral Key

### ISSUE THREAD

**Issue by MedianAura** [muhmiauwauWOW/GreatVaultList#5]
With Astral Key installed 

https://www.curseforge.com/wow/addons/astral-keys

The addon show like this. 

![image](https://github.com/user-attachments/assets/e8410c31-9fd1-49ad-bb95-b78fade5f620)

**Comment by muhmiauwau** [comment]
Hello, thank for reporting that issue. 
Unfortunately i could not find an incompatible issue with Astral Key installed.
But i fix a few problems that could cause that kind of issue. 

Please try again with version 2.0.3 and hopefully it will work

**Comment by MedianAura** [comment]
The issue seem to have changed with the lastest update of AstralKey but now I have this issue : 

1x ...eGreatVaultList/Libs/LibLodash/LibLodash.lua:26: attempt to call local 'a8' (a nil value)
[string "@GreatVaultList/Libs/LibLodash/LibLodash.lua"]:26: in function `cast'
[string "@GreatVaultList/Libs/LibLodash/LibLodash.lua"]:26: in function <...eGreatVaultList/Libs/LibLodash/LibLodash.lua:26>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: in function `sort'
[string "@GreatVaultList/mixins.lua"]:433: in function `SetSortOrder'
[string "@GreatVaultList/mixins.lua"]:493: in function `init'
[string "@GreatVaultList/GreatVaultList.lua"]:189: in function `updateData'
[string "@GreatVaultList/GreatVaultList.lua"]:87: in function `showWindow'
[string "@GreatVaultList/GreatVaultList.lua"]:96: in function `toggleWindow'
[string "@GreatVaultList/GreatVaultList.lua"]:112: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5479: in function `ChatEdit_ParseText'
...
[string "=[C]"]: in function `RunMacroText'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:445: in function `handler'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:667: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:649>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:704: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:702>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:726: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:707>
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/SecureHandlers.lua"]:266: in function <Blizzard_FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/SecureHandlers.lua"]:296: in function <Blizzard_FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals:
G = nil
H = "Tahmah"
a8 = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = ""
(*temporary) = "attempt to call local 'a8' (a nil value)"
a = <table> {
 unionFind = <table> {
 }
 _VERSION = "0.02"
}

**Comment by MedianAura** [comment]
The latest update seem to have fixed everything. I also figured there was a bug with this weakAuras

https://wago.io/bRl2gJIgz

That seemed to break the addon but with that update aswell everythis work perfectly.

Thank You
