### ISSUE TITLE
Not possible to sort on Raids column

### ISSUE THREAD

**Issue by keflatbn** [muhmiauwauWOW/GreatVaultList#9]
Hi,
Thanks for a great QoL addon, just stated using it and with already 13 level 80, this addon helps alot <3

I noticed that you can sort on all columns except for Raids, is that intentional or a small bug? 
![image](https://github.com/user-attachments/assets/83e77370-4fc2-400d-a30c-cec7d1708df8)

No big deal, but if its an easy fix and not intentional, then heres a heads-up.

Using version 2.4.3

**Comment by muhmiauwau** [comment]
Hello, thank you for remembering me on this TODO. Unfortunately that is more a missing feature than a bug.  Perhaps I find time to implement the sorting function for the raid column this week. But I am glad to hear that this addon helps your with your characters.
